### ISSUE TITLE
Discerning Clones From Current Universes and Split Universes

### ISSUE THREAD

**Issue by cr4zyc0dy** [HarambeStudios/Project-Spacetime#53]
Was thinking maybe we could recolor the split clones, so we could implement puzzles in which the alternate clone is required to hit a switch and not the current universe clone.

**Comment by Toltar** [comment]
Awesome! We will discuss this in a team meeting soon.

**Comment by Toltar** [comment]
Since we are running out of time, I am closing this issue.
